from .login import *
from .register import *
from .home import *
from .coilHandling import *
from .inventoryLocation import *
from .labelStatus import *
from .labelHandling import *
from .reports import *
from .usersManagement import *
from .labelTraceability import *
from .skuHandling import *
from .orderHandling import *
from .lineHandling import *
from .requestHandling import *
from .apiHandling import *
from .coilRequestHandling import *
