from .login import *
from .register import *
from .home import *
from .coilHandling import *
from .inventoryLocation import *
from .labelStatus import *
from .labelHandling import *
from .reports import *
from .depletionOfCoils import *
from .usersManagement import *
from .labelTraceability import *
