# Generated by Django 4.1.5 on 2023-01-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuervo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
