# Generated by Django 4.1.5 on 2023-01-18 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuervo', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='coilProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='coilStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='coilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='inventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=20)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('FK_coil_id', models.ForeignKey(help_text='Linked Coil', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coil')),
                ('FK_inventoryLocation_id', models.ForeignKey(help_text='Linked Inventory Location', on_delete=django.db.models.deletion.CASCADE, to='cuervo.inventorylocation')),
            ],
        ),
        migrations.CreateModel(
            name='labelStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='labelTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('FK_inventoryLocation_id', models.ForeignKey(help_text='Linked Inventory Location', on_delete=django.db.models.deletion.CASCADE, to='cuervo.inventorylocation')),
                ('FK_labelStatus_id', models.ForeignKey(help_text='Linked Label Status', on_delete=django.db.models.deletion.CASCADE, to='cuervo.labelstatus')),
                ('FK_label_id', models.ForeignKey(help_text='Linked Label', on_delete=django.db.models.deletion.CASCADE, to='cuervo.label')),
                ('user_id', models.ForeignKey(help_text='Linked User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='FK_labelStatus_id',
            field=models.ForeignKey(help_text='Linked Label Status', on_delete=django.db.models.deletion.CASCADE, to='cuervo.labelstatus'),
        ),
        migrations.AddField(
            model_name='label',
            name='last_edit_user',
            field=models.ForeignKey(help_text='Linked User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='coilTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('FK_coilProvider_id', models.ForeignKey(help_text='Linked Coil Provider', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coilprovider')),
                ('FK_coilStatus_id', models.ForeignKey(help_text='Linked Coil Status', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coilstatus')),
                ('FK_coilType_id', models.ForeignKey(help_text='Linked Coil Type', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coiltype')),
                ('FK_coil_id', models.ForeignKey(help_text='Linked Coil', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coil')),
                ('user_id', models.ForeignKey(help_text='Linked User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coil',
            name='FK_coilProvider_id',
            field=models.ForeignKey(help_text='Linked Coil Provider', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coilprovider'),
        ),
        migrations.AddField(
            model_name='coil',
            name='FK_coilStatus_id',
            field=models.ForeignKey(help_text='Linked Coil Status', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coilstatus'),
        ),
        migrations.AddField(
            model_name='coil',
            name='FK_coilType_id',
            field=models.ForeignKey(help_text='Linked Coil Type', on_delete=django.db.models.deletion.CASCADE, to='cuervo.coiltype'),
        ),
        migrations.AddField(
            model_name='coil',
            name='last_edit_user',
            field=models.ForeignKey(help_text='Linked User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
